### ISSUE TITLE
Flask file hosting

### ISSUE THREAD

**Issue by willweatherman** [JWWeatherman/yeticold#1]
[onlineyeti.txt](https://github.com/JWWeatherman/yeticold/files/3817030/onlineyeti.txt)

**Comment by willweatherman** [comment]
[startup.txt](https://github.com/JWWeatherman/yeti/files/3698213/startup.txt)

Change startup.txt to startup.py and run with python3 startup.py

**Comment by JWWeatherman** [comment]
tar -czf myfile.tar.gz /etc/dir1 /var/www/html /home/somedir

**Comment by JWWeatherman** [comment]
switch c to x

**Comment by JWWeatherman** [comment]
utxo = subprocess.Popen(['~/flaskapp/bitcoin-0.18.1/bin/bitcoin-cli listunspent'],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        utxo = json.loads(utxo[0])[0]
        newstr = utxo['txid'] + ','
        newstr = newstr + str(utxo['vout']) + ','
        newstr = newstr + utxo['address'] + ','
        newstr = newstr + utxo['scriptPubKey'] + ','
        newstr = newstr + str(utxo['amount']) + ','

**Comment by JWWeatherman** [comment]
global firstqrcode
    global secondqrcode
    global thirdqrcode
    global firstqrname
    global secondqrname
    global thirdqrname
    global privkeylist
    if request.method == 'GET':
        rpc = RPC()
        trans = secondqrcode #### parse this
        trans = trans.decode("utf-8")
        trans = trans.split(",")
        trans[1] = int(trans[1])
        trans[4] = float(trans[4])
        #trans[0] = txid
        #trans[1] = vout
        #trans[2] = address 
        #trans[3] = scrirptPubKey
        #trans[4] = amount
        firstqrcode = firstqrcode.decode("utf-8")
        secondqrcode = secondqrcode.decode("utf-8")
        thirdqrcode = thirdqrcode.decode("utf-8")
        amo = ((trans[4] / 3) - 0.00003)
        newamo = (trans[4] * (2 / 3))
        print(trans[4])
        print(amo)
        print(newamo)
        amo = "{:.8f}".format(float(amo))
        newamo = "{:.8f}".format(float(newamo))
        print(amo)
        print(newamo)
        transonehex = rpc.createrawtransaction([{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode}], [{firstqrcode: amo}, {trans[2] : newamo }])
        newamo = (trans[4] * (1 / 3))
        newamo = "{:.8f}".format(float(newamo))
        transtwohex = rpc.createrawtransaction([{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode}], [{firstqrcode: amo}, {trans[2] : newamo }])
        newamo = 0
        transthreehex = rpc.createrawtransaction([{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode}], [{firstqrcode: amo}, {trans[2] : newamo }])
        print(type(transonehex))
        print(type([privkeylist[0], privkeylist[1], privkeylist[2]]))
        print([privkeylist[0], privkeylist[1], privkeylist[2]])
        print(privkeylist[0])
        print(privkeylist[1])
        print(privkeylist[2])
        print(secondqrcode)
        print(type(secondqrcode))
        print(transtwohex)
        print(transthreehex)
        transone = rpc.signrawtransactionwithkey(transonehex, [privkeylist[0], privkeylist[1], privkeylist[2]], [{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode, "amount": trans[4]}])
        transtwo = rpc.signrawtransactionwithkey(transtwohex, [privkeylist[2], privkeylist[3], privkeylist[4]], [{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode, "amount": trans[4]}])
        transthree = rpc.signrawtransactionwithkey(transtwohex, [privkeylist[4], privkeylist[5], privkeylist[6]], [{ "txid": trans[0], "vout": trans[1], "scriptPubKey": trans[3], "redeemScript": thirdqrcode, "amount": trans[4]}])
        firstqrcode = transone
        secondqrcode = transtwo
        thirdqrcode = transthree
        randomnum = str(random.randrange(0,1000000))
        firstqrname = randomnum
        secondqrname = randomnum
        thirdqrname = randomnum
        print(firstqrcode)
        print(secondqrcode)
        print(thirdqrcode)
        qr = qrcode.QRCode(
               version=1,
               error_correction=qrcode.constants.ERROR_CORRECT_L,
               box_size=10,
               border=4,
        )
        qr.add_data(firstqrcode)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        home = os.getenv("HOME")
        img.save(home + '/flaskapp/static/firsttransqrcode'+firstqrname+'.png')
        route = url_for('static', filename='firsttransqrcode' + firstqrname + '.png')

**Comment by JWWeatherman** [comment]
firstqrcode = firstqrcode.decode("utf-8")
        secondqrcode = secondqrcode.decode("utf-8")
        thirdqrcode = thirdqrcode.hex()
        minerfee = float(rpc.estimatesmartfee(6)["feerate"])
        kilobytespertrans = 0.01
        amo = ((trans[4] / 3) - (minerfee * kilobytespertrans))

**Comment by JWWeatherman** [comment]
3EVrVmuEtztWK88zYCo1iyk4fTiKMaY5Ez

**Comment by JWWeatherman** [comment]
[bitcoin.txt](https://github.com/JWWeatherman/yeti/files/3768029/bitcoin.txt)

**Comment by JWWeatherman** [comment]
[Uploading Dtemplates.zip…]()

**Comment by JWWeatherman** [comment]
[Dtemplates.zip](https://github.com/JWWeatherman/yeti/files/3804721/Dtemplates.zip)

**Comment by JWWeatherman** [comment]
@app.route("/displayfirsttransqrcode", methods=['GET', 'POST'])
def displayfirsttransqrcode():
    global firstqrcode
    global secondqrcode
    global thirdqrcode
    global firstqrname
    global secondqrname
    global thirdqrname
    global privkeylist
    global xprivlist
    global transnum
    global amount
    ##### GEN TRANS CODE
    if request.method == 'GET':
        print(secondqrcode)
        xpublist = secondqrcode.decode("utf-8").split(',')[1:]
        print(xpublist)
        xpublist[6] = xpublist[6].split('))')[0]
        response = subprocess.Popen(['~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli getdescriptorinfo "wsh(multi(3,'+xprivlist[0]+'/*,'+xprivlist[1]+'/*,'+xprivlist[2]+'/*,'+xpublist[3]+','+xpublist[4]+','+xpublist[5]+','+xpublist[6]+'))"'],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        print('~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli getdescriptorinfo "wsh(multi(3,'+xprivlist[0]+'/*,'+xprivlist[1]+'/*,'+xprivlist[2]+'/*,'+xpublist[3]+','+xpublist[4]+','+xpublist[5]+','+xpublist[6]+'))"')
        print("getdescriptorinfo")
        print(response)
        response = response[0].decode("utf-8")
        response = json.loads(response)
        checksum = response["checksum"]
        response = subprocess.Popen(['~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli  importmulti \'[{ "desc": "wsh(multi(3,'+xprivlist[0]+'/*,'+xprivlist[1]+'/*,'+xprivlist[2]+'/*,'+xpublist[3]+','+xpublist[4]+','+xpublist[5]+','+xpublist[6]+'))#'+ checksum +'", "timestamp": "now", "range": [0,999], "watchonly": false, "label": "test" }]\' \'{"rescan": true}\''],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        print('~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli  importmulti \'[{ "desc": "wsh(multi(3,'+xprivlist[0]+'/*,'+xprivlist[1]+'/*,'+xprivlist[2]+'/*,'+xpublist[3]+','+xpublist[4]+','+xpublist[5]+','+xpublist[6]+'))#'+ checksum +'", "timestamp": "now", "range": [0,999], "watchonly": false, "label": "test" }]\' \'{"rescan": true}\'')
        print("importmulti")
        print(response)
        rpc = RPC()
        trans = firstqrcode #### parse this
        trans = trans.decode("utf-8")
        trans = trans.split(",")
        trans[1] = int(trans[1])
        trans[4] = float(trans[4])
        #trans[0] = txid
        #trans[1] = vout
        #trans[2] = changeaddress
        #trans[3] = scrirptPubKey
        #trans[4] = amount
        #trans[5] = recpipentaddress
        #trans[6] = witnessScript
        minerfee = float(rpc.estimatesmartfee(6)["feerate"])
        kilobytespertrans = 0.01
        amo = ((trans[4] / 3) - (minerfee * kilobytespertrans))
        amount = (trans[4] * (1 / 3))
        amo = "{:.8f}".format(float(amo))
        newamo = "{:.8f}".format(float(amount))
        response = subprocess.Popen(['~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli  createrawtransaction \'[{ "txid": "'+trans[0]+'", "vout": '+str(trans[1])+'}]\' \'[{"'+trans[5]+'" : '+str(amo)+'}, {"'+trans[2]+'" : '+str(newamo)+' }]\''],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        print()
        print('~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli  createrawtransaction \'[{ "txid": "'+trans[0]+'", "vout": '+str(trans[1])+'}]\' \'[{"'+trans[5]+'" : '+str(amo)+'}, {"'+trans[2]+'" : '+str(newamo)+' }]\'')
        print(response)
        print("create raw transaction")
        transonehex = response[0].decode("utf-8")[:-1]
        print(transonehex)
        response = subprocess.Popen(['~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli signrawtransactionwithwallet '+transonehex+' \'[{ "txid": "'+trans[0]+'", "vout": '+str(trans[1])+', "scriptPubKey": "'+trans[3]+'", "witnessScript": "'+trans[6][:-1]+'", "amount": "'+str(trans[4])+'" }]\''],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        print('~/flaskapp/bitcoin-0.19.0rc1/bin/bitcoin-cli signrawtransactionwithwallet '+transonehex+' \'[{ "txid": "'+trans[0]+'", "vout": '+str(trans[1])+', "scriptPubKey": "'+trans[3]+'", "witnessScript": "'+trans[6][:-1]+'", "amount": "'+str(trans[4])+'" }]\'')
        print("signrawtrans")
        print(response)
        print("result")
        transone = json.loads(response[0].decode("utf-8"))
        print(transone)
        firstqrcode = transone
        randomnum = str(random.randrange(0,1000000))
        firstqrname = randomnum
        qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
        )
        qr.add_data(secondqrcode)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        home = os.getenv("HOME")
        img.save(home + '/flaskapp/static/firsttransqrcode'+firstqrname+'.png')
        route = url_for('static', filename='firsttransqrcode' + firstqrname + '.png')
    if request.method == 'POST':
        transnum = 1
        return redirect('/restartwallet')
    return render_template('displayfirsttransqrcode.html', qrdata=firstqrcode, route=route)
