### ISSUE TITLE
Random number counter is in UI broken

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#110]
This is step 6 in Level 1. YHgetseed is the template. As you enter 1s and 0s you should see the number counter tick up, but it remains at 0 \ 256 (also the slash here is a back slash and should be a forward slash). Please verify the fix doesn't need to be applied to L2 and L3 as well.

<img width="668" alt="Screen Shot 2021-01-09 at 6 27 54 PM" src="https://user-images.githubusercontent.com/32912678/104110757-c64f4800-52a8-11eb-8f79-39f6f8d283e7.png">

**Comment by willweatherman** [comment]
Fixed.
