### ISSUE TITLE
CopySeed.html fixes

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#116]
> When you see "Data CD successfully burnt" click <b>Close</b> and remove and then label the CD "Seed 1"

Should just be labeled "Seed", not "Seed 1"

> Ensure that you have a "yetiseed.text" on each of your five CDs labeled "Seed" before clicking Next.

file name is "yetiseed.txt"

**Comment by JWWeatherman** [comment]
Just verified this is correct in CopySeed.html so I'm assuming it was fixed and not closed by @willweatherman (staaap it)
