### ISSUE TITLE
step 11 L3 throws an error on a full archive node

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#117]
The rescan takes so long that the page times out and throws an error.

500 Internal Server Error: error: Could not connect to the server 127.0.0.1:8332 (error code 0 - "timeout reached") Make sure the bitcoind server is running and that you are connecting to the correct RPC port. . response for function: ~/yeticold/bitcoin/bin/bitcoin-cli -rpcwallet=yetiwalletpub importdescriptors '[{ "desc":

**Comment by willweatherman** [comment]
Fixed.
