### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#122]
When going through the "load wallet" flow for level 3 the url is missing:

load.yeticold.com 

<img width="752" alt="Screen Shot 2021-01-26 at 6 37 14 PM" src="https://user-images.githubusercontent.com/32912678/105920519-835dd600-6005-11eb-9d36-b060ecf17da4.png">

**Comment by willweatherman** [comment]
Load wallet flow does not use URLs.
