### ISSUE TITLE
Step 5 of "watch only" flow

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#124]
Should not display the red bullet point. Please make sure there are no regressions on this as I really don't want to find another bug on this page in another flow.

<img width="748" alt="Screen Shot 2021-01-26 at 7 17 47 PM" src="https://user-images.githubusercontent.com/32912678/105923913-2f55f000-600b-11eb-9b3c-5951adde1740.png">

**Comment by willweatherman** [comment]
Fixed.
