### ISSUE TITLE
How can I achieve yeticold "levels" without trusting the code?

### ISSUE THREAD

**Issue by donnlee** [JWWeatherman/yeticold#128]
I learned from @JWWeatherman that twitter:@benwestgate published copy-paste steps that are equivalent to yeticold.

This is appealing to me because (1) it's easier to read the native Bitcoin Core commands than parsing the commands/calls from yeticold's code, (2) I'm hopeful the copy-paste commands include help about what each command does/is for (so I can learn), (3) I wouldn't have to trust the ~300 lines of yeticode.

I read the README and FAQ, and I didn't find Ben's copy-paste recipe. Could it be added to the FAQ please?
Thank you

**Comment by Rspigler** [comment]
Ben's bash script is here:  https://github.com/BenWestgate/yeti.Bash

Please note that this is not battle-tested yet, nor an official part of Yeti, however it likely will be at one point and we greatly appreciate all of Ben's contributions!

**Comment by JWWeatherman** [comment]
Added!

**Comment by JWWeatherman** [comment]
https://github.com/JWWeatherman/yeticold/blob/master/FAQ.md#why-should-i-trust-yeti-with-my-life-savings
