### ISSUE TITLE
If you decide to do watch only you should encrypt the drive with a decent password

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#130]

**Comment by Rspigler** [comment]
ACK

**Comment by JWWeatherman** [comment]
We should test to see if it takes significantly longer to sync a full node on SSD if it has drive encryption. If not we should do that.

**Comment by JWWeatherman** [comment]
The downside is that if it makes setup take longer your have a security cost to that too.

**Comment by JWWeatherman** [comment]
New instructions are on the erase step and they inform the user to encrypt the drive and set a strong password if they need to keep a watch only device. But we also do not recommend they take this step and instead continue with erasing the loptop.
