### ISSUE TITLE
Bitcoin.conf

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#137]
Should be:

> assumevalid=0
> dbcache=1000
> proxy=127.0.0.1:9050
> avoidpartialspends=1
> maxapsfee=0.002

`assumevalid` validates the entire chain (can still prune)
`dbcache`: increasing the database cache allows for faster sync.  Is really only limited by machine RAM. Default is 450 megabytes. 1000 is a significant increase and we don't have to worry about crashing old computers.
`proxy`: Anonymizes all outgoing connections, including DNS requests.  Also disables incoming connections. We already have this.
`avoidpartialspends`: Group outputs by address, selecting all or none, instead of selecting on a per-output basis. Improves privacy at expense of higher transaction fees. Not necessary if following best practices of non-address reuse.  Also not necessary currently (since we require selecting complete UTXO) - but we should have now for when we fix
`maxapsfee`:  the amount of additional bitcoin at which APS will be avoided.  Open to debating amount.

**Comment by Rspigler** [comment]
whatever prune value we recently updated to as well

**Comment by Rspigler** [comment]
custom dbcache and prune values from Ben's code here:
https://github.com/JWWeatherman/yeticold/issues/145

**Comment by JWWeatherman** [comment]
I don't want to change defaults from bitcoin core unless we are certain it is needed. So I'd rather leave assume valid as default (even though there is some case for making it zero I don't think it is obvious). 145 has a fix for dbcache. I think our next change related to "avoid partial spends" and "maxapsfee" will be to provide mixing instructions when spending from Yeti. Probably through Liquid, but it requires more investigation.

**Comment by Rspigler** [comment]
Makes sense!
