### ISSUE TITLE
Update Yeti Hot and Yeti Warm Instructions

### ISSUE THREAD

**Issue by willweatherman** [JWWeatherman/yeticold#140]
Yeti Hot and Warm should tell the user they can just power off the laptop if they have encrypted the drive and set a strong password instead of erasing it.

**Comment by Rspigler** [comment]
I agree with Yeti Level 1 - it's a low quantity single sig wallet.  Persistence gives users the ability to have a 'spending' wallet to send funds to from higher levels, without constantly restoring/wiping.

I disagree with the idea for Level 2 - it is a multisig wallet, but single device.  Keeping the keys on a single device to sign transactions is strictly a security downgrade, and there shouldn't be a greater cash flow need for a persistent wallet?

Possibly a more mobile need, but there has been discussion of a 'Level 0' for that - single sig Core on a mobile phone.

**Comment by willweatherman** [comment]
Agreed to an extent we should probably just tell the user to set up their laptop as a watch-only wallet after there done signing transactions instead of just powering it off. In the best-case scenario, we would have a mobile watch-only to go with all three levels.

**Comment by JWWeatherman** [comment]
The idea here is that if someone needs to spend regularly Yeti is still a good option. Here is the text I added to the erase instructions:

<li>If you need to spend and receive bitcoin often you can skip this  step and instead set a strong password, enable automatic updates, and encrypt   your hard drive. This is not recommended as is not as secure.</li>
         <li>If you need to receive, but you do net need to send, you can  complete this step to erase your Secondary laptop only and set a strong  password, enable automatic updates and encrypt the hard drive of your Primary   laptop. This is not recommended as it weakens privacy, but this does leave you  with a "watch-only" node that can be used to see changes to your balance and  make deposits to your Yeti wallet.</li>

@Rspigler please close if you agree this is solid.

**Comment by Rspigler** [comment]
> The idea here is that if someone needs to spend regularly Yeti is still a good option

Definitely agree.  I guess I always just assumed that the recommended flow would be to send from higher levels a few times a year into a persistent Level 1 and mobile Level 0.  Very much like the text.  As long as this is only recommended for Level 1 and 2 (and not Level 3 and 4), ACK for me.

**Comment by Rspigler** [comment]
I can't close, @willweatherman has to
