### ISSUE TITLE
Fix Bitcoin Core Verification

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#146]
1. Download the Signing Key
2. Check signature of SHA256SUMS
3. Check that valid signature is w/ Signing Key (using full fingerprint; not Short/Long Key ID)
4. Check hash of application

Doesn't currently check fingerprint (shoutout to @BenWestgate)

**Comment by willweatherman** [comment]
Thanks for catching this and helping to fix this @BenWestgate.
