### ISSUE TITLE
Change Instances of "Used Laptop"

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#148]
Do to possibilities of low level malware, change any reference to recommendations of getting a used laptop (to save money), to purchasing a new one and returning it instead.

**Comment by JWWeatherman** [comment]
Step 1 on each of the 3 levels now makes no reference to "used laptops" and recommends returning the laptop after setup to save money. Assigning to @willweatherman for code review and push to production.

**Comment by willweatherman** [comment]
There are no suggestions to use a used laptop.
