### ISSUE TITLE
Step 34 Erase Your Laptop

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#149]
https://guide3.yeticold.com/Cold/Guide/step4

> 8. Confirm that the hard drive is "not frozen". If it's "frozen" contact support at "yeticold.slack.com".

Add information on how to fix, then suggest contacting support if not solved.  I believe suspending power (top right corner), waiting, then continuing typically solves.

**Comment by willweatherman** [comment]
I have tried that with a laptop that was frozen and it had no effect so I am better off just getting them on a call and trying to figure it out from there. At least until we have confirmed a reliable way to fix it.

**Comment by Rspigler** [comment]
Cool, didn't realize, thanks for the comment.
