### ISSUE TITLE
Add documentation for using yeticold with testnet?

### ISSUE THREAD

**Issue by surfer190** [JWWeatherman/yeticold#158]
I did not find any references to using yeticold with the testnet.

Would it be the case of restarting and setting `testnet=1 ` in `bitcoin.conf`?

If so I will add a section to the FAQ?

**Comment by willweatherman** [comment]
You are correct on how to start Bitcoin core in testnet mode except I don't want to complicate anything. Any testing I'd prefer to happen on mainnet with small amounts anyway.
