### ISSUE TITLE
L3 - Step 13 - Seed pages need spot for "Seed Number"

### ISSUE THREAD

**Issue by CKHODL** [JWWeatherman/yeticold#162]
Hi!

I have been working through Level 3. I noticed that on Step 13, the printable seed pages should have a box where I can write my Seed number. 

If I do not do this then:
- when i need to validate my seeds I don't know which is which.
- When i store my seed CDs with my Seed paper, I might inadvertently store the wrong seeds together - worst case, each location will be storing 2 seeds rather than 1.

I suggest a box to write the seed number as opposed to pre-printing it incase I screw up and want to re-print a seed page.

**Comment by willweatherman** [comment]
Fixed https://github.com/JWWeatherman/yeticold/commit/dd7384ee322b2e037cd7a5a32069ca8e7e55549e.
