### ISSUE TITLE
Check seed page - error easily missed

### ISSUE THREAD

**Issue by CKHODL** [JWWeatherman/yeticold#165]
When entering seeds into the validator, if you enter the incorrect seed and hit next, the page looks the same, but there is a small red error telling you need to try it again. 

When I ran through the setup, I missed this error 3 times, resulting in me wasting 10 minutes or so entering seeds 4,5 and 6 instead of 3 (where i was stuck).

Ideally the seed validator would validate the page using javascript prior to pressing next, but a quick fix for this issue is just to make the error text bigger and bolder

**Comment by willweatherman** [comment]
Fixed https://github.com/JWWeatherman/yeticold/commit/27fd0670cef058288da8c0a92e559f204e7a2f72
