### ISSUE TITLE
Recovery instructions: printed text colors are too light

### ISSUE THREAD

**Issue by ryenski** [JWWeatherman/yeticold#171]
On my particular system, when printing the recovery instructions (printpage.html template), the font colors are so light as to be borderline illegible. I was able to use Firefox dev tools to change the font color to #000, which helped somewhat. 

It would probably be helpful for others if the text color was true black instead of dark grey.

**Comment by willweatherman** [comment]
Fixed https://github.com/JWWeatherman/yeticold/commit/472d31d6f0b15b26a404880497a519933a2c0478.
Thanks, I thought all browsers defaulted to black, apparently not.
