### ISSUE TITLE
Create a "verify address" script

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#39]
This is a script you can run on an offline device that will scan the descriptor and display a list of all of the 1000 addresses so that someone can verify that the address they are about to send to on the online device is correct.

We want this to be different from the disconnected laptop because that laptop holds private keys and we want it to be erased as soon as possible.  This "address verification device" will be optional, but might be worth the trouble for very large amounts.

To start this flow we should add a "utilities" link at the bottom of the landing page of yeticold.com and this utilities page will have a link to things like "address verification device setup."

**Comment by willweatherman** [comment]
Not needed anymore.
