### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by Furunodo** [JWWeatherman/yeticold#49]
- [ ] add a simple test framework (this will help with below tasks)
- [ ] make code much DRYer (Don't Repeat Yourself)
- [ ] make it more pythonic
- [ ] add a free software license
- [ ] remove `.DS_Store` files from repo (`.gitignore` is good for that)

**Comment by willweatherman** [comment]
Fixed

**Comment by ndalliard** [comment]
License?
