### ISSUE TITLE
Setup is broken on secondary and primary

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#51]
<img width="395" alt="Screen Shot 2020-02-01 at 4 01 38 PM" src="https://user-images.githubusercontent.com/32912678/73598944-2b80b200-450c-11ea-9b79-7183aeea4b66.png">

**Comment by JWWeatherman** [comment]
<img width="1070" alt="Screen Shot 2020-02-01 at 4 02 22 PM" src="https://user-images.githubusercontent.com/32912678/73598950-3dfaeb80-450c-11ea-92de-7dc2858f39ae.png">

**Comment by JWWeatherman** [comment]
This was after selecting and downloading the test blockchain.

**Comment by willweatherman** [comment]
Fixed.
