### ISSUE TITLE
Difficult to learn about Yeti

### ISSUE THREAD

**Issue by bitcoinhodler** [JWWeatherman/yeticold#52]
I'm intrigued by this system, yet I find it unnecessarily difficult to research it without actually going through all the steps of the process. For example I started going through the cold storage process and reached this page: https://cold.yeticold.com/Cold/step6

But there's no link to advance beyond that without actually running the software.

I would like a way to read more about the process and what's involved before I decide whether or not to use Yeti.

**Comment by Moller40** [comment]
I very much agree. There could be a demo mode that is entirely web based that take you through all steps, but without the need to write anything down. Then it would be much easier to do it for real after.

**Comment by JWWeatherman** [comment]
My plan is to create a walk through video, but if someone else wanted to do it that would awesome ;)

**Comment by bitcoinhodler** [comment]
I was thinking more like a design document, explaining the choices and tradeoffs made in the system.

**Comment by JWWeatherman** [comment]
That was my goal with the readme:
https://github.com/JWWeatherman/yeticold/blob/master/README.md

I was also thinking that a "bitcoin storage" threat model would be a good idea, but at this point I'm not sure I will ever get to it.

**Comment by bitcoinhodler** [comment]
In that case the video is probably a good way to demonstrate.

**Comment by sahilc0** [comment]
I 100% agree with @bitcoinhodler, at the same time I think the readme is fantastic. Maybe a quickfix (until video/detailed documentation) could be linking to the readme in a "Tip" box somewhere on the Steps page? 
![image](https://user-images.githubusercontent.com/8256062/79594073-41c0f780-8091-11ea-893a-8eb3853f6088.png)

(that would help new users who aren't going to the github)

**Comment by fresheneesz** [comment]
>> I was thinking more like a design document, explaining the choices and tradeoffs made in the system.

> That was my goal with the readme

I think in order to really do that properly, all the major steps need to be written down, so that each step can potentially have a bit of explanation and discussion of trade offs. 

It would certainly be easier to understand the protocol if the full set of steps were easily accessible in written form. Video walk throughs can be good, but they are much harder to go back and reference (they're not very searchable). 

Making it easy for people to look through the steps would also make it easier for reviewers and contributors to catch mistakes and improve the protocols.

**Comment by JDSmaster** [comment]
Hi all - it looks I may be a late to the show but I agree with the other comments that there is a lack of clear description how the full installation process looks like so people know what happens and what to expect. Video will do well as well as a written instructions describing the actual installation process. I experienced some problems which I posted under another more relevant topic. While we all appreciate this being done on a voluntary basis, I personally like the idea but still not dare to fully go live given the unknown steps ahead and how it actually works in practice.

In one of your earlier podcasts on the topic, you made a comparison with Glacier protocol and expressed some general reservations with it. Could you make a short pros/cons or simple comparison between the two?

Many thanks and appreciate the work - on face of it, this looks like a most credible and secure approach.

**Comment by JWWeatherman** [comment]
We now have a video walkthrough on the first step of each level. 

@JDSmaster join us is slack for general discussions about Glacier, etc.

https://join.slack.com/t/yeticold/shared_invite/zt-hisfxrra-BZzrYCDnqFv6whxVn~6FQQ
