### ISSUE TITLE
www.yeticold.com has invalid SSL cert

### ISSUE THREAD

**Issue by bitcoinhodler** [JWWeatherman/yeticold#53]
> Websites prove their identity via certificates. Tor Browser does not trust this site because it uses a certificate that is not valid for www.yeticold.com. The certificate is only valid for the following names: bco.yeticold.com, cold.yeticold.com, disc.yeticold.com, hot.yeticold.com, off.yeticold.com, rec.yeticold.com, warm.yeticold.com, yeticold.com, yeticold.org

**Comment by willweatherman** [comment]
Thank you @bitcoinhodler. This has been fixed.

**Comment by bitcoinhodler** [comment]
I confirm the issue is fixed. Thank you for the quick response!
