### ISSUE TITLE
localhost Issue After Running YetiCold.py Script

### ISSUE THREAD

**Issue by esprograms** [JWWeatherman/yeticold#54]
After I run the YetiCold.py script (python3 ~/yeticold/scripts/YetiCold.py), a new window in my web browser opens up and gives me the error "This site can’t be reached. localhost refused to connect."

The terminal says:

Traceback (most recent call last):
  File "/home/pi/yeticold/appyeticold.py", line 8, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory
Opening in existing browser session.

If additional information is needed in order to help, please let me know.

Thank you!

**Comment by JWWeatherman** [comment]
Click “try again.” The browser opens before the web server is ready.

**Comment by esprograms** [comment]
Thanks, JW. I tried that, but it still didn't work. I deleted the yeticold directory and started over. Below is the full output from the terminal. It looks like everything is working but the error related to the import error at the bottom ("ImportError: libjasper.so.1"), but I'm not sure if that import would affect the webserver running. Thanks again for your help.

pi@raspberrypi:~ $ python3 ~/yeticold/scripts/YetiCold.py
Already up to date.
/bin/sh: 1: snap: not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-venv is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sshpass is already the newest version (1.06-1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libzbar0 is already the newest version (0.22-1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.3.5.8-1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: python-bitcoinrpc in /usr/local/lib/python3.7/dist-packages (1.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: opencv-python in ./.local/lib/python3.7/site-packages (4.1.1.26)
Requirement already satisfied: numpy>=1.16.2 in /usr/lib/python3/dist-packages (from opencv-python) (1.16.2)
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease         
Reading package lists... Done
Installing updates. This could take an hour without feedback.
sudo: unattended-upgrade: command not found
--2020-02-09 09:00:45--  https://bitcoincore.org/bin/bitcoin-core-0.19.0.1/bitcoin-0.19.0.1-x86_64-linux-gnu.tar.gz
Resolving bitcoincore.org (bitcoincore.org)... 107.191.99.5, 198.251.83.116
Connecting to bitcoincore.org (bitcoincore.org)|107.191.99.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31944271 (30M) [application/octet-stream]
Saving to: ‘/home/pi/yeticold/bitcoin-0.19.0.1-x86_64-linux-gnu.tar.gz’

bitcoin-0.19.0.1-x86_64-linux-gnu 100%[============================================================>]  30.46M  2.46MB/s    in 11s     

2020-02-09 09:00:56 (2.84 MB/s) - ‘/home/pi/yeticold/bitcoin-0.19.0.1-x86_64-linux-gnu.tar.gz’ saved [31944271/31944271]

bitcoin-0.19.0.1/
bitcoin-0.19.0.1/bin/
bitcoin-0.19.0.1/bin/bitcoin-cli
bitcoin-0.19.0.1/bin/bitcoind
bitcoin-0.19.0.1/bin/bitcoin-qt
bitcoin-0.19.0.1/bin/bitcoin-tx
bitcoin-0.19.0.1/bin/bitcoin-wallet
bitcoin-0.19.0.1/bin/test_bitcoin
bitcoin-0.19.0.1/include/
bitcoin-0.19.0.1/include/bitcoinconsensus.h
bitcoin-0.19.0.1/lib/
bitcoin-0.19.0.1/lib/libbitcoinconsensus.so
bitcoin-0.19.0.1/lib/libbitcoinconsensus.so.0
bitcoin-0.19.0.1/lib/libbitcoinconsensus.so.0.0.0
bitcoin-0.19.0.1/README.md
bitcoin-0.19.0.1/share/
bitcoin-0.19.0.1/share/man/
bitcoin-0.19.0.1/share/man/man1/
bitcoin-0.19.0.1/share/man/man1/bitcoin-cli.1
bitcoin-0.19.0.1/share/man/man1/bitcoind.1
bitcoin-0.19.0.1/share/man/man1/bitcoin-qt.1
bitcoin-0.19.0.1/share/man/man1/bitcoin-tx.1
bitcoin-0.19.0.1/share/man/man1/bitcoin-wallet.1
--2020-02-09 09:00:58--  https://bitcoin.org/bin/bitcoin-core-0.19.0.1/SHA256SUMS.asc
Resolving bitcoin.org (bitcoin.org)... 138.68.248.245
Connecting to bitcoin.org (bitcoin.org)|138.68.248.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1895 (1.9K) [application/octet-stream]
Saving to: ‘/home/pi/yeticold/SHA256SUMS.asc’

SHA256SUMS.asc                    100%[============================================================>]   1.85K  --.-KB/s    in 0s      

2020-02-09 09:00:59 (13.0 MB/s) - ‘/home/pi/yeticold/SHA256SUMS.asc’ saved [1895/1895]

sha256sum: WARNING: 20 lines are improperly formatted
1
gpg: key 90C8019E36C2E964: "Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
rm: cannot remove '/home/pi/.bitcoin/wallets/yeticold*': No such file or directory
rm: cannot remove '/home/pi/.bitcoin/yeticold*': No such file or directory
rm: cannot remove '/home/pi/yeticoldwallet*': No such file or directory
 --disable-quic --enable-tcp-fast-open --ppapi-flash-path=/usr/lib/chromium-browser/libpepflashplayer.so --ppapi-flash-args=enable_stagevideo_auto=0 --ppapi-flash-version=
Traceback (most recent call last):
  File "/home/pi/yeticold/appyeticold.py", line 8, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory
Opening in existing browser session.

**Comment by willweatherman** [comment]
@esprograms What version of ubuntu and hardware are you using?

Thanks-
Will.

**Comment by akc2020** [comment]
Running into a similar issue with YetiCold.py: No module named 'cv2'
While the script is running there is a red error message:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nd6mnsay/opencv-python/
Shortly before that: No module named 'skbuild'
Ubuntu version is 18.04.5 LTS.

**Comment by JDSmaster** [comment]
Hi all 
it looks that this issue has been unresolved (please send a link if it was elsewhere). Few observations and questions from my experimental test run - I experienced similar problems as described above:

1.When starting the process I got stuck after Step 5 - after the execution of the Python script the new browser window opens with ‘Try Again’ button but nothing happens after that upon clicking after several minutes. Never got to Step 6 or 7.

2.You suggest Ubuntu as the main OS. Is there any issue to have any other Debian/Ubuntu ‘compatible’ distribution (eg other *ubuntu DE derivatives, MX or Mint)?

3.The installation script downloads Bitcoin Core 0.19 while the current stable version is 0.20. Is there a version of the script which assumes that Bitcoin Core is already installed and running as well as Tor? Could the existence of BtcCore (fully synced chain)/Tor be the reason for the problem above?

4.How to uninstall / reverse the changes that have been made by the script if one wants to go back to previous pre-Yeti status? Is is simply to remove the Yeticold folder? 

Thanks!

**Comment by willweatherman** [comment]
Fixed
