### ISSUE TITLE
Don't erase all Phrases if entering one wrong at the Check Private Key steps

### ISSUE THREAD

**Issue by Moller40** [JWWeatherman/yeticold#55]
If I enter one wrong phrase at the Check Private Key steps, the page is reloaded and all I entered is removed. It could be that I just mixed Phrase Four and Five, and it is annoying that all is removed so I can't check and have to type all again.
These steps are cumbersome enough anyway.

**Comment by JWWeatherman** [comment]
Agreed. We need to store the seed words entered and repopulate them on error reload.
