### ISSUE TITLE
Wallet page not aligned

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#58]
I think this is the 4th time this bug has come up. Fix it using best practice and do the research to know what is the best practice. 
<img width="526" alt="Screen Shot 2020-02-18 at 12 29 36 PM" src="https://user-images.githubusercontent.com/32912678/74761923-e4542a00-524a-11ea-8bdd-d8de34c4b18f.png">

**Comment by willweatherman** [comment]
Page dose not exist anymore.
