### ISSUE TITLE
Question regarding use and seed packets

### ISSUE THREAD

**Issue by wispyco** [JWWeatherman/yeticold#64]
When referring to seed packets in the steps, what are they exactly? All I have is the same private key written in the NATO phonetic alphabet on paper and in a txt file. Did I miss a step? I saved the same txt to 4 different usbs and have the same things on paper with each key. 

I dumped my private key from bitcoin core and it doesn't match the private key generated here, and I am not including the checksum. What may I be doing wrong? The private key I am dumping is a receiving address inside my yeti warm wallet. Is the private key for the wallet or the receiving address I am a little confused.

I can provide more information if needed, but need some help on why my private keys don't match.

**Comment by wispyco** [comment]
I had closed yeti running in the terminal reran and my wallet is gone, I don't have any btc in it yet. I am just trying to understand how this all works before I put anything in it. When I try and restore my wallet with my seed txt file I hit enter and get the following error `Internal Server Error` So not sure what's going on there. Does yet have to always be running for Bitcoin core to run. Would it be better to just install bitcoin core natively and store my private key, I dont quote understand what yeti is doing.

**Comment by JWWeatherman** [comment]
Seed packets contain one of your private keys and your wallet descriptor. As long as you have 3 of them you can access your bitcoin.

yeti helping you interact with bitcoin core. 

For support hit us up in slack:
https://t.co/AAXBlq6RsU?amp=1
