### ISSUE TITLE
Bitcoin core opening over and over on fresh install - Ubuntu Desktop 20.04.1 LTS 

### ISSUE THREAD

**Issue by shade-7** [JWWeatherman/yeticold#83]
Running Ubuntu Desktop 20.04.1 LTS
After running this in Terminal: 
python3 ~/yeticold/scripts/YetiCold.py
Bitcoin core opens and begins downloading blockchain history. 
Terminal displays the attached text over and over again. 

Many instances of Bitcoin core are opened with ~5 second delay, and the user is left to actively close them as they open. 

Failed to workaround by typing Ctrl+C, Ctrl+X, and Esc into Terminal. 
Worked around by closing Terminal Window and all instances of Bitcoin Core, and (if I remember correctly) I re-ran YetiCold.py. 

![WIN_20201012_13_15_45_Pro](https://user-images.githubusercontent.com/72764813/95787589-afd82700-0c8e-11eb-85c9-220ce74ff6f7.jpg)

**Comment by willweatherman** [comment]
This is a known issue caused when your bitcoin rpc password/username are not the same as the ones in yeticold. I will fix this in the next refactor.

**Comment by shade-7** [comment]
> This is a known issue caused when your bitcoin rpc password/username are not the same as the ones in yeticold. I will fix this in the next refactor.

**Comment by shade-7** [comment]
Thanks I did not see it as a huge problem. I still have ambition to make a Yeti Cold walkthrough video. Will keep you updated if I do so.
