### ISSUE TITLE
Import cv2 error appyeticold.py

### ISSUE THREAD

**Issue by shade-7** [JWWeatherman/yeticold#84]
ModuleNotFoundError: No module names 'cv2' reported when running step 8 on secondary laptop. 

This is the possible reason. What do you recommend doing? 

https://stackoverflow.com/questions/46610689/how-to-import-cv2-in-python3

**Comment by shade-7** [comment]
Traced it back to an error I got in the previous step. This is probably just a Surface tablet problem with Ubuntu more than anything else. 

Error I am getting: 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ml7fefgy/opencv-python

Let me know of any advice, and whether I should record this elsewhere, like in a "support" section.

**Comment by willweatherman** [comment]
Creating an issue in Github will notify us in the slack GitHub notifications section. I am not sure what is causing this issue but I do know that backporting to an older cv2(OpenCV-python) version often helps.

**Comment by JWWeatherman** [comment]
Going to close as this is probably not an issue we can fix in Yeti.
