### ISSUE TITLE
Store config in environment variables

### ISSUE THREAD

**Issue by j-chimienti** [JWWeatherman/yeticold#87]
Issue: 

config values stored in the code making it impossible to have custom deploys.

I have bitcoin core synced and would like to run `python3 appyeticold.py` on my machine but cannot configure variables (rpc auth, bitcoin-cli, datadir,...)

**Comment by j-chimienti** [comment]
Basically I have bitcoin synced on machine, and I want to skip initialization and test out wallet utils and use my configuration settings.

**Comment by willweatherman** [comment]
We don't want it to be part of the UI to configure these things but in the ugly utils/varibles.py file you can change these yourself. I also don't want to use the environment to store the variables because it's so hard to debug. Espacial with out access to the laptop.
