### ISSUE TITLE
Level 1 doesn't accept additional entropy

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#88]
"Skip"
<img width="805" alt="Screen Shot 2020-12-24 at 1 22 18 PM" src="https://user-images.githubusercontent.com/32912678/103102666-0ea11180-45eb-11eb-9fa5-abf3d6eb22fc.png">
 works fine, but if you try to add additional entropy we should make the box turn green as soon as there are 256 numbers and we should enable the next button.

**Comment by willweatherman** [comment]
Fixed
