### ISSUE TITLE
When restoring a yetiwarm wallet yeti rescans twice

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#94]
On the final page where we enter the 3rd seed yeti starts a rescan. Then on the payg YWRrescanwallet you click "next" and there is an additional rescan. We should be able to do this only once I think.

**Comment by willweatherman** [comment]
The first one is a quick one that is called by importdescriptors RPC command has no effect in scanning for your transactions. The second one does an actual rescan and can take a while.
