### ISSUE TITLE
Only show the final bullet point for Level 1 and Level 2

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#95]
For level 3 we really want the user to leave this screen and only click next when the secondary laptop instructs the user to click next. I 

<img width="910" alt="Screen Shot 2020-12-26 at 5 16 13 PM" src="https://user-images.githubusercontent.com/32912678/103160026-456b5900-479e-11eb-9e0f-5845cf82ad95.png">

**Comment by willweatherman** [comment]
Fixed
