### ISSUE TITLE
Copy paste is broken on level 3 recovery

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yeticold#96]
The second command should be something like python3 ~/yeticold/initialize.py YetiColdSecondaryRecover

Instead it is:

python3 ~/yeticold/initialize.py YeticoldSecondaryRecovery

Please test this this time - I'm getting annoyed with these changes that are clearly not being tested well.

<img width="910" alt="Screen Shot 2020-12-26 at 8 14 28 PM" src="https://user-images.githubusercontent.com/32912678/103161915-11e8f880-47b7-11eb-87b5-761798465e19.png">

**Comment by gaetawoo** [comment]
The way I had written it before, which I think Will used wholesale, was that it is case-insensitive. It converts all arguments to lower() and then compares. Not sure if that is still what is being done.

**Comment by willweatherman** [comment]
Fixed
